apiVersion: apps/v1  # Указывает API-версию для создания Deployment.
kind: Deployment  # Определяет ресурс Deployment для управления состоянием приложения.
metadata:
  name: connector-app  # Имя Deployment, используемое для идентификации.
spec:
  replicas: 1  # Количество реплик приложения.
  selector:
    matchLabels:
      app: connector-app  # Метка для связи с подами.
  template:  # Шаблон для создания подов.
    metadata:
      labels:
        app: connector-app  # Метка, назначаемая создаваемым подам.
    spec:
      containers:
      - name: connector-app-container  # Имя контейнера.
        image: timmyalvice8/python-connector  # !Заменить на свой!!!
        ports:
        - containerPort: 5000  # Открытие порта 5000 внутри контейнера.
        env:  # Переменные окружения для контейнера.
        
        # Postgres env
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secrets  # Секрет, содержащий имя пользователя PostgreSQL.
              key: postgres-user  # Ключ в секрете для имени пользователя.
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets  # Секрет, содержащий пароль PostgreSQL.
              key: postgres-password  # Ключ в секрете для пароля.
        - name: PG_DBNAME
          valueFrom:
            configMapKeyRef:
              name: configs 
              key: POSTGRES_DB 
        - name: PG_HOST
          valueFrom:
            configMapKeyRef:
              name: configs 
              key: POSTGRES_HOST
        - name: PG_PORT
          valueFrom:
            configMapKeyRef:
              name: configs 
              key: POSTGRES_PORT

        # Kafka env
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: configs
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: configs
              key: KAFKA_TOPIC       

---
apiVersion: v1
kind: Service
metadata:
  name: connector-app-service
spec:
  selector:
    app: connector-app
  ports:
  - protocol: TCP
    port: 8080  # Порт, по которому будет доступен сервис
    targetPort: 5000  # Порт, на который будут направляться запросы внутри контейнера
  type: ClusterIP  # Тип сервиса

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: connector-app-ingress
spec:
  rules:
  - host: localhost  # Замените на ваш домен или IP
    http:
      paths:
      - path: /fetch
        pathType: Prefix
        backend:
          service:
            name: connector-app-service
            port:
              number: 8080