apiVersion: apps/v1  # Указывает API-версию для создания Deployment.
kind: Deployment  # Определяет ресурс Deployment для управления состоянием приложения.
metadata:
  name: spark-process-deployment  # Имя Deployment, используемое для идентификации.
spec:
  replicas: 1  # Количество реплик приложения.
  selector:
    matchLabels:
      app: spark-process  # Метка для связи с подами.
  template:  # Шаблон для создания подов.
    metadata:
      labels:
        app: spark-process  # Метка, назначаемая создаваемым подам.
    spec:
      containers:
      - name: spark-process-container  # Имя контейнера.
        image: smv/pyspark-processer  # Docker-образ для Spark-консьюмера. !!! Заменить на свой !!!
        ports:
        - containerPort: 5001  # Открытие порта 5001 внутри контейнера.
        env:  # Переменные окружения для контейнера.

        # Clickhouse env
        - name: CLICKHOUSE_HOST
          valueFrom:
            configMapKeyRef:
              name: configs
              key: CLICKHOUSE_HOST
        - name: CLICKHOUSE_PORT
          valueFrom:
            configMapKeyRef:
              name: configs
              key: CLICKHOUSE_PORT 
        - name: CLICKHOUSE_DATABASE
          valueFrom:
            configMapKeyRef:
              name: configs
              key: CLICKHOUSE_DATABASE
        - name: CLICKHOUSE_INPUT_TABLE
          valueFrom:
            configMapKeyRef:
              name: configs
              key: CLICKHOUSE_TABLE 
        - name: CLICKHOUSE_OUTPUT_TABLE
          valueFrom:
            configMapKeyRef:
              name: configs
              key: CLICKHOUSE_RESULT_TABLE 
